version: "3"

services:
  nginx:
    image: ghcr.io/devawaves/www-nginx:latest
    ports:
      - 80:80
    container_name: nginx
    restart: always
  date:
    image: ghcr.io/devawaves/www-date:latest
    container_name: date
    restart: always
    environment:
      NODE_ENV: production
  astro:
    image: ghcr.io/devawaves/www-astro:latest
    container_name: astro
    restart: always
    environment:
      NODE_ENV: production
      HOST: '0.0.0.0'
      PORT: 3000
