version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx/latest
    ports:
      - 80:80
    container_name: nginx
    restart: always
  date:
    build:
      context: ./date
      dockerfile: Dockerfile
    image: date/latest
    container_name: date
    restart: always
    environment:
      NODE_ENV: production