name: build website

on:
  workflow_dispatch: null
  push:
    branches: dev
    paths:
      - VERSION
    tags-ignore:
      - "*"

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: checkout code
        uses: actions/checkout@main
      - name: log into ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: build all docker images
        run: |
          docker build ./date --tag ghcr.io/devawaves/www-date:$(cat VERSION)
          docker build ./nginx --tag ghcr.io/devawaves/www-nginx:$(cat VERSION)
          docker build ./astro --tag ghcr.io/devawaves/www-astro:$(cat VERSION)
      - name: publish all docker images
        run: |
          docker tag ghcr.io/devawaves/www-date:$(cat VERSION) ghcr.io/devawaves/www-date:latest
          docker push ghcr.io/devawaves/www-date:$(cat VERSION)
          docker push ghcr.io/devawaves/www-date:latest

          docker tag ghcr.io/devawaves/www-nginx:$(cat VERSION) ghcr.io/devawaves/www-nginx:latest
          docker push ghcr.io/devawaves/www-nginx:$(cat VERSION)
          docker push ghcr.io/devawaves/www-nginx:latest

          docker tag ghcr.io/devawaves/www-astro:$(cat VERSION) ghcr.io/devawaves/www-astro:latest
          docker push ghcr.io/devawaves/www-astro:$(cat VERSION)
          docker push ghcr.io/devawaves/www-astro:latest
